#footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
robot_radius: 0.07  #圆形机器人半径 直径12cm,半径6cm

observation_sources: scan #设置导航中所使用的传感器，这里可以用逗号形式来区分开很多个传感器，例如激光雷达，碰撞传感器，超声波传感器等
scan:
  data_type: LaserScan #激光雷达数据类型
  topic: scan #该激光雷达发布的话题名
  marking: true #是否可以使用该传感器来标记障碍物
  clearing: true #是否可以使用该传感器来清除障碍物标记为自由空间

map_type: costmap

transform_tolerance: 0.2

obstacle_layer:
 enabled: true
 obstacle_range: 2.5 #障碍物范围 机器人只会更新其地图包含距离移动基座2.5米以内的障碍物的信息
 raytrace_range: 3.0 #光线追踪范围 机器人将尝试清除3米外的空间，在代价地图中清除3米外的障碍物
 inflation_radius: 0.08 #膨胀半径 如果机器人经常撞到障碍物就需要增大该值!!!!!，若经常无法通过狭窄地方就减小该值!!!!!
 track_unknown_space: false
 combination_method: 1

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.08  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"