global_costmap:
  global_frame: map #全局代价地图需要在哪个坐标系下运行
  robot_base_frame: base_footprint #在全局代价地图中机器人本体的基坐标系，就是机器人上的根坐标系
  update_frequency: 1.0 #10.0 #全局代价地图更新频率，一般全局代价地图更新频率设置的比较小
  publish_frequency: 0.5 #发布频率
  transform_tolerance: 0.5 #坐标系间的转换可以忍受的最大延时
  static_map: true #配置是否使用map_server提供的地图来初始化，一般全局地图都是静态的，需要设置为true
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

#http://wiki.ros.org/costmap_2d?distro=noetic
 
